/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Backup.java
 *
 * Created on Mar 30, 2013, 4:38:18 PM
 */

package the.ear.trainer;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Geniuez
 * 
 */
public class Backup extends javax.swing.JDialog {

    /** Creates new form Backup */
    public Backup(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        generalPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fileNameTextField = new javax.swing.JTextField();
        backupLabel = new javax.swing.JLabel();
        browseButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        saveInTextField = new javax.swing.JTextField();
        generalPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        resoreLabel = new javax.swing.JLabel();
        restoreNameTextField = new javax.swing.JTextField();
        browseButton1 = new javax.swing.JButton();
        directoryTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Backup/ Restore");

        generalPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Create a Backup"));

        jLabel1.setText("File Name");

        fileNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileNameTextFieldActionPerformed(evt);
            }
        });

        backupLabel.setForeground(new java.awt.Color(94, 79, 174));
        backupLabel.setText("Create a Backup");
        backupLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backupLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backupLabelMouseClicked(evt);
            }
        });

        browseButton.setText("Browse");
        browseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("Save In");

        javax.swing.GroupLayout generalPanel2Layout = new javax.swing.GroupLayout(generalPanel2);
        generalPanel2.setLayout(generalPanel2Layout);
        generalPanel2Layout.setHorizontalGroup(
            generalPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(generalPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(generalPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(generalPanel2Layout.createSequentialGroup()
                        .addGroup(generalPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(generalPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fileNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(saveInTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(23, Short.MAX_VALUE))
                    .addGroup(generalPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(browseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(backupLabel)
                        .addGap(31, 31, 31))))
        );
        generalPanel2Layout.setVerticalGroup(
            generalPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(generalPanel2Layout.createSequentialGroup()
                .addGroup(generalPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fileNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGroup(generalPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(generalPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(generalPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(saveInTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(browseButton)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, generalPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(backupLabel)
                        .addGap(24, 24, 24))))
        );

        generalPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Restore"));

        jLabel4.setText("File Name");

        resoreLabel.setForeground(new java.awt.Color(94, 79, 174));
        resoreLabel.setText("Restore");
        resoreLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        resoreLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resoreLabelMouseClicked(evt);
            }
        });

        restoreNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restoreNameTextFieldActionPerformed(evt);
            }
        });

        browseButton1.setText("Browse");
        browseButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Directory");

        javax.swing.GroupLayout generalPanel3Layout = new javax.swing.GroupLayout(generalPanel3);
        generalPanel3.setLayout(generalPanel3Layout);
        generalPanel3Layout.setHorizontalGroup(
            generalPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(generalPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(generalPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(generalPanel3Layout.createSequentialGroup()
                        .addGroup(generalPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(generalPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(directoryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(restoreNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, generalPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(browseButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(resoreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        generalPanel3Layout.setVerticalGroup(
            generalPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(generalPanel3Layout.createSequentialGroup()
                .addGroup(generalPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(restoreNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(generalPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(directoryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(generalPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(browseButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, generalPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(resoreLabel)
                        .addGap(10, 10, 10)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(generalPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(generalPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(generalPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(generalPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fileNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fileNameTextFieldActionPerformed

    private void browseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseButtonActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        int result = fileChooser.showSaveDialog(this);
        if(result==JFileChooser.APPROVE_OPTION) {
            fileNameTextField.setText(fileChooser.getSelectedFile().getName()+".sql");
            saveInTextField.setText(fileChooser.getCurrentDirectory().toString());

        }

    }//GEN-LAST:event_browseButtonActionPerformed

    private void backupLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backupLabelMouseClicked
        Database backupDatabase=new Database();
        String path=saveInTextField.getText()+"/"+fileNameTextField.getText();
        boolean bool;
        try {
            bool = backupDatabase.getBackup("ear_trainer", "root", "", path);
            if(bool){
                JOptionPane.showMessageDialog(this, "Backup created successfully", "Message", JOptionPane.PLAIN_MESSAGE,new ImageIcon("./src/icons/success.png"));
            }else{
                JOptionPane.showMessageDialog(this, "Could not create the backup", "Error!", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            Logger.getLogger(Backup.class.getName()).log(Level.SEVERE, null, ex);

        }

    }//GEN-LAST:event_backupLabelMouseClicked

    private void restoreNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restoreNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_restoreNameTextFieldActionPerformed

    private void resoreLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resoreLabelMouseClicked




        String path=directoryTextField.getText()+"/"+restoreNameTextField.getText();
      
        Database backupDatabase=new Database();
        try {
            boolean result = backupDatabase.restoreBackup("ear_trainer", "root", "", path);
            if(result){
                JOptionPane.showMessageDialog(this, "Backup Restore successfully", "Message", JOptionPane.PLAIN_MESSAGE,new ImageIcon("./src/icons/success.png"));
            }
        } catch (Exception ex) {
            Logger.getLogger(Backup.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Could not restore the backup", "Error!", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_resoreLabelMouseClicked

    private void browseButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseButton1ActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        int result = fileChooser.showOpenDialog(this);
        if(result==JFileChooser.APPROVE_OPTION) {
            restoreNameTextField.setText(fileChooser.getSelectedFile().getName());
            directoryTextField.setText(fileChooser.getCurrentDirectory().toString());


        }
    }//GEN-LAST:event_browseButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Backup dialog = new Backup(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backupLabel;
    private javax.swing.JButton browseButton;
    private javax.swing.JButton browseButton1;
    private javax.swing.JTextField directoryTextField;
    private javax.swing.JTextField fileNameTextField;
    private javax.swing.JPanel generalPanel2;
    private javax.swing.JPanel generalPanel3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel resoreLabel;
    private javax.swing.JTextField restoreNameTextField;
    private javax.swing.JTextField saveInTextField;
    // End of variables declaration//GEN-END:variables

}
