/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package the.ear.trainer;

import java.awt.BorderLayout;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
//import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.JFrame;

/**
 *
 * @author Suchira
 */
public class PracticeButtonPanel extends javax.swing.JPanel {

    private MainMenuJFrame mainFrame;
    /**
     * Creates new form PracticeButtonPanel
     */
    public PracticeButtonPanel(MainMenuJFrame mainFrame) {
        this.mainFrame = mainFrame;
        initComponents();
        this.add(leftPanel, BorderLayout.WEST);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        rightPanel = new javax.swing.JPanel();
        borderPanel = new javax.swing.JPanel();
        nextButton = new javax.swing.JButton();
        chooseComboBox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        startingFromComboBox = new javax.swing.JComboBox();
        levelLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        categoryComboBox = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        levelComboBox = new javax.swing.JComboBox();
        leftPanel = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout(10, 10));

        rightPanel.setPreferredSize(new java.awt.Dimension(87, 324));

        javax.swing.GroupLayout rightPanelLayout = new javax.swing.GroupLayout(rightPanel);
        rightPanel.setLayout(rightPanelLayout);
        rightPanelLayout.setHorizontalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        rightPanelLayout.setVerticalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        add(rightPanel, java.awt.BorderLayout.EAST);

        borderPanel.setLayout(new java.awt.GridBagLayout());

        nextButton.setText("Next");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(55, 132, 22, 22);
        borderPanel.add(nextButton, gridBagConstraints);

        chooseComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Western Music", "Eastern Music" }));
        chooseComboBox.setToolTipText("");
        chooseComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseComboBoxActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 72, 0, 22);
        borderPanel.add(chooseComboBox, gridBagConstraints);

        jLabel2.setText("From where you want to start from?");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 36;
        gridBagConstraints.ipady = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 26, 0, 0);
        borderPanel.add(jLabel2, gridBagConstraints);

        startingFromComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Specific Level", "Beginning" }));
        startingFromComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startingFromComboBoxActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 72, 0, 22);
        borderPanel.add(startingFromComboBox, gridBagConstraints);

        levelLabel.setText("Select the level");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 137;
        gridBagConstraints.ipady = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 26, 0, 0);
        borderPanel.add(levelLabel, gridBagConstraints);

        jLabel1.setText("Choose Western or Eastern");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 77;
        gridBagConstraints.ipady = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 26, 0, 0);
        borderPanel.add(jLabel1, gridBagConstraints);

        categoryComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Scales", "Chords", "Intervals", "Notes" }));
        categoryComboBox.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        categoryComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryComboBoxActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 47;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 72, 0, 22);
        borderPanel.add(categoryComboBox, gridBagConstraints);

        jLabel4.setText("Select the category");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 116;
        gridBagConstraints.ipady = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 26, 0, 0);
        borderPanel.add(jLabel4, gridBagConstraints);

        levelComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Level 1", "Level 2", "Level 3", "Level 4" }));
        levelComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                levelComboBoxActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 56;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(19, 72, 0, 22);
        borderPanel.add(levelComboBox, gridBagConstraints);

        add(borderPanel, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 83, Short.MAX_VALUE)
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 324, Short.MAX_VALUE)
        );

        add(leftPanel, java.awt.BorderLayout.WEST);
        remove(leftPanel);
        add(leftPanel, java.awt.BorderLayout.WEST);
    }// </editor-fold>//GEN-END:initComponents

    private void chooseComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chooseComboBoxActionPerformed

    private void startingFromComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startingFromComboBoxActionPerformed
        String selectedItem = startingFromComboBox.getSelectedItem().toString();
        if(selectedItem != "Specific Level"){
            levelLabel.setVisible(false);
            levelComboBox.setVisible(false);
        }
        else{
            levelLabel.setVisible(true);
            levelComboBox.setVisible(true);  
        }
    }//GEN-LAST:event_startingFromComboBoxActionPerformed

    private void categoryComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryComboBoxActionPerformed
        
    }//GEN-LAST:event_categoryComboBoxActionPerformed

    private void levelComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_levelComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_levelComboBoxActionPerformed

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        /*Assuming all the required areas has been recorded accordingly*/

        String startingFrom = startingFromComboBox.getSelectedItem().toString();
        if(startingFrom == "Beginning"){
            Category category = new Category(categoryComboBox.getSelectedItem().toString());
            
            Level level = new Level(1);
//            Level level2 = new Level(2);
//            Level level3 = new Level(3);
//            Level level4 = new Level(4);
//            Level level5 = new Level(5);
//            Level level6 = new Level(6);
            category.addNewLevel(level);
//            category.addNewLevel(level2);
//            category.addNewLevel(level3);
//            category.addNewLevel(level4);
//            category.addNewLevel(level5);
//            category.addNewLevel(level6);
            
            ExercisePanel exercisePanel = new ExercisePanel(category, 1);
            mainFrame.repaintDynamicPanel(exercisePanel);
        }
        else if(startingFrom == "Specific Level"){
            Category category = new Category(categoryComboBox.getSelectedItem().toString());
            String[] levelString = levelComboBox.getSelectedItem().toString().split(" ");
            int levelNumber = Integer.parseInt(levelString[1]);
            
            Level level = new Level(levelNumber);
//            Level level2 = new Level(++levelNumber);
//            Level level3 = new Level(++levelNumber);
//            Level level4 = new Level(++levelNumber);
//            Level level5 = new Level(++levelNumber);
//            Level level6 = new Level(++levelNumber);
            category.addNewLevel(level);
//            category.addNewLevel(level2);
//            category.addNewLevel(level3);
//            category.addNewLevel(level4);
//            category.addNewLevel(level5);
//            category.addNewLevel(level6);
//            
            ExercisePanel exercisePanel = new ExercisePanel(category, level.getLevelNumber());
            mainFrame.repaintDynamicPanel(exercisePanel);
        }
    }//GEN-LAST:event_nextButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel borderPanel;
    private javax.swing.JComboBox categoryComboBox;
    private javax.swing.JComboBox chooseComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JComboBox levelComboBox;
    private javax.swing.JLabel levelLabel;
    private javax.swing.JButton nextButton;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JComboBox startingFromComboBox;
    // End of variables declaration//GEN-END:variables
}
