/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package the.ear.trainer;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import the.ear.trainer.UserHandler;

/**
 *
 * @author Suchira
 */
public class SearchJPanel extends javax.swing.JPanel {

    List<Object[]> searchList;
    private DefaultTableModel usersTableModel;
    private UserHandler uHandler = new UserHandler();
    private String username;

    /**
     * Creates new form searchJPanel
     */
    public SearchJPanel() {
        initComponents();
        usersTableModel = (DefaultTableModel)usersTable.getModel();
        
//        grantPanel.setVisible(true);
//        permissionLabel1.setVisible(false);
//        permissionButton1.setEnabled(false);
//        infoLabel.setVisible(false);
//        permissionLabel.setVisible(false);
//        permissionButton.setVisible(false);
        
//        setPreferredSize(new Dimension(880, 456));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchTextField = new javax.swing.JTextField();
        searchingButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        usersTable = new javax.swing.JTable();
        grantPanel = new javax.swing.JPanel();
        permissionLabel = new javax.swing.JLabel();
        permissionButton = new javax.swing.JButton();
        infoLabel = new javax.swing.JLabel();
        permissionLabel1 = new javax.swing.JLabel();
        permissionButton1 = new javax.swing.JButton();

        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(880, 456));

        searchingButton.setText("SEARCH");
        searchingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchingButtonActionPerformed(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setOpaque(false);

        usersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "UserName", "Priority"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        usersTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        usersTable.setOpaque(false);
        usersTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usersTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(usersTable);
        if (usersTable.getColumnModel().getColumnCount() > 0) {
            usersTable.getColumnModel().getColumn(0).setPreferredWidth(10);
        }

        grantPanel.setOpaque(false);

        permissionLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        permissionLabel.setForeground(new java.awt.Color(0, 51, 51));
        permissionLabel.setText("Grant Admin Permission For The Selected User?");

        permissionButton.setText("GRANT");
        permissionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                permissionButtonActionPerformed(evt);
            }
        });

        infoLabel.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        infoLabel.setForeground(new java.awt.Color(255, 0, 0));
        infoLabel.setText("User Is Already an Admin");

        permissionLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        permissionLabel1.setForeground(new java.awt.Color(0, 51, 51));
        permissionLabel1.setText("Grant User Permission For The Selected User?");

        permissionButton1.setText("GRANT");
        permissionButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                permissionButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout grantPanelLayout = new javax.swing.GroupLayout(grantPanel);
        grantPanel.setLayout(grantPanelLayout);
        grantPanelLayout.setHorizontalGroup(
            grantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, grantPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(grantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(grantPanelLayout.createSequentialGroup()
                        .addComponent(permissionLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addComponent(permissionButton1))
                    .addGroup(grantPanelLayout.createSequentialGroup()
                        .addComponent(permissionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(permissionButton)))
                .addGap(30, 30, 30))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, grantPanelLayout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(infoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(104, 104, 104))
        );
        grantPanelLayout.setVerticalGroup(
            grantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(grantPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(grantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(permissionLabel)
                    .addComponent(permissionButton))
                .addGap(7, 7, 7)
                .addGroup(grantPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(permissionButton1)
                    .addComponent(permissionLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(infoLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 672, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(searchingButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(grantPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchingButton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(grantPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchingButtonActionPerformed
        // TODO add your handling code here:
        searchList = uHandler.getUsers();
        System.out.println("list: " + searchList.toString());
        usersTableModel.setRowCount(0);
        
        if(searchTextField.getText() != null){
            String text = new String(searchTextField.getText());
            for (Object[] row : searchList) {
            for (int i = 0; i < 3; i++) {
                if(row[i] != null){
                    Pattern pattern=Pattern.compile(text,Pattern.CASE_INSENSITIVE);
                    Matcher matcher=pattern.matcher(row[i].toString());
                    if(matcher.find()){
                        usersTableModel.addRow(row);
                        System.out.println("ROW: " + row.toString());
                        break;
                    }
                }
            }
        }
        }
    }//GEN-LAST:event_searchingButtonActionPerformed

    private void usersTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usersTableMouseClicked
        // TODO add your handling code here:`
        System.out.println("ID - " + (String)usersTableModel.getValueAt(usersTable.getSelectedRow(), 0));
        username = (String)usersTableModel.getValueAt(usersTable.getSelectedRow(), 1);
        String priority = (String)usersTableModel.getValueAt(usersTable.getSelectedRow(), 2);
        System.out.println("SELECTED priority: " + priority);
        
        if(priority.equals("Admin")){
            grantPanel.setVisible(true);
            permissionLabel1.setVisible(true);
            permissionButton1.setVisible(true);
            permissionLabel.setVisible(false);
            permissionButton.setVisible(false);
            infoLabel.setText("User Is Already an Admin");
            
        }
        if(priority.equals("User")){
            grantPanel.setVisible(true);
            permissionLabel1.setVisible(false);
            permissionButton1.setVisible(false);
            permissionLabel.setVisible(true);
            permissionButton.setVisible(true);
            infoLabel.setText("User Is Already an User");
        }
        
        MainMenuJFrame.getMainMenuJFrame(User.getUser()).repaintDynamicPanel(this);
    }//GEN-LAST:event_usersTableMouseClicked

    private void permissionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_permissionButtonActionPerformed
        // TODO add your handling code here:
        uHandler.grantPermission(username, "Admin");
    }//GEN-LAST:event_permissionButtonActionPerformed

    private void permissionButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_permissionButton1ActionPerformed
        // TODO add your handling code here:
        uHandler.grantPermission(username, "User");

    }//GEN-LAST:event_permissionButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel grantPanel;
    private javax.swing.JLabel infoLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton permissionButton;
    private javax.swing.JButton permissionButton1;
    private javax.swing.JLabel permissionLabel;
    private javax.swing.JLabel permissionLabel1;
    private javax.swing.JTextField searchTextField;
    private javax.swing.JButton searchingButton;
    private javax.swing.JTable usersTable;
    // End of variables declaration//GEN-END:variables
}
