/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package the.ear.trainer;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
//import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.JFrame;

/**
 *
 * @author Suchira
 */
public class PracticeButtonPanel extends javax.swing.JPanel {

    private MainMenuJFrame mainFrame;
    /**
     * Creates new form PracticeButtonPanel
     */
    public PracticeButtonPanel(MainMenuJFrame mainFrame) {
        this.mainFrame = mainFrame;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        chooseComboBox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        startingFromComboBox = new javax.swing.JComboBox();
        nextButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        categoryComboBox = new javax.swing.JComboBox();
        levelComboBox = new javax.swing.JComboBox();
        levelLabel = new javax.swing.JLabel();

        jLabel1.setText("Choose Western or Eastern");

        chooseComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Western Music", "Eastern Music" }));
        chooseComboBox.setToolTipText("");
        chooseComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseComboBoxActionPerformed(evt);
            }
        });

        jLabel2.setText("From where you want to start from?");

        startingFromComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Specific Level", "Beginning", "Where Left Off" }));
        startingFromComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startingFromComboBoxActionPerformed(evt);
            }
        });

        nextButton.setText("Next");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Select the category");

        categoryComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Scale", "Chords", "Intervals", "Notes" }));
        categoryComboBox.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        categoryComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryComboBoxActionPerformed(evt);
            }
        });

        levelComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Level 1", "Level 2", "Level 3", "Level 4" }));
        levelComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                levelComboBoxActionPerformed(evt);
            }
        });

        levelLabel.setText("Select the level");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(310, 310, 310)
                        .addComponent(nextButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)
                                .addComponent(chooseComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(startingFromComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(levelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(levelComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(categoryComboBox, 0, 115, Short.MAX_VALUE))))))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chooseComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(startingFromComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(categoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(levelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(levelComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(nextButton)
                .addGap(50, 50, 50))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void chooseComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chooseComboBoxActionPerformed

    private void startingFromComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startingFromComboBoxActionPerformed
        String selectedItem = startingFromComboBox.getSelectedItem().toString();
        if(selectedItem != "Specific Level"){
            levelLabel.setVisible(false);
            levelComboBox.setVisible(false);
        }
        else{
            levelLabel.setVisible(true);
            levelComboBox.setVisible(true);  
        }
    }//GEN-LAST:event_startingFromComboBoxActionPerformed

    private void categoryComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryComboBoxActionPerformed
        
    }//GEN-LAST:event_categoryComboBoxActionPerformed

    private void levelComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_levelComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_levelComboBoxActionPerformed

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        /*Assuming all the required areas has been recorded accordingly*/    
        
        
        //Objects that should be created here
        //'Category', 'Level'

//        ExerciseLoader loader = ExerciseLoader.getInstance();
//            try {
//                System.out.println("SELECTED: " + categoryComboBox.getSelectedItem().toString());
//                List<Exercise> list = loader.loadFilesInALevel(categoryComboBox.getSelectedItem().toString(), 1);
//                System.out.println("Correct answer: " + list.get(0).getCorrectAnswer());
//            } catch (Exception ex) {
//                Logger.getLogger(PracticeButtonPanel.class.getName()).log(Level.SEVERE, null, ex);
//            }        

        String startingFrom = startingFromComboBox.getSelectedItem().toString();
        if(startingFrom == "Beginning"){
            Category category = new Category(categoryComboBox.getSelectedItem().toString());
            
            Level level = new Level(1);
            Level level2 = new Level(2);
            Level level3 = new Level(3);
            Level level4 = new Level(4);
            Level level5 = new Level(5);
            Level level6 = new Level(6);
            category.addNewLevel(level);
            category.addNewLevel(level2);
            category.addNewLevel(level3);
            category.addNewLevel(level4);
            category.addNewLevel(level5);
            category.addNewLevel(level6);
            
            ExercisePanel exercisePanel = new ExercisePanel(category, 1);
            mainFrame.repaintDynamicPanel(exercisePanel);
        }
        else if(startingFrom == "Specific Level"){
            Category category = new Category(categoryComboBox.getSelectedItem().toString());
            String[] levelString = levelComboBox.getSelectedItem().toString().split(" ");
            int levelNumber = Integer.parseInt(levelString[1]);
            
            Level level = new Level(levelNumber);
            Level level2 = new Level(++levelNumber);
            Level level3 = new Level(++levelNumber);
            Level level4 = new Level(++levelNumber);
            Level level5 = new Level(++levelNumber);
            Level level6 = new Level(++levelNumber);
            category.addNewLevel(level);
            category.addNewLevel(level2);
            category.addNewLevel(level3);
            category.addNewLevel(level4);
            category.addNewLevel(level5);
            category.addNewLevel(level6);
            
            ExercisePanel exercisePanel = new ExercisePanel(category, level.getLevelNumber());
            mainFrame.repaintDynamicPanel(exercisePanel);
        }
    }//GEN-LAST:event_nextButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox categoryComboBox;
    private javax.swing.JComboBox chooseComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JComboBox levelComboBox;
    private javax.swing.JLabel levelLabel;
    private javax.swing.JButton nextButton;
    private javax.swing.JComboBox startingFromComboBox;
    // End of variables declaration//GEN-END:variables
}
